In [8]:
import cv2
import numpy as np

In [5]:
img = cv2.imread('pepega.png')

In [15]:
arr = np.array((np.mean(img), np.std(img)))

In [16]:
np.save('model.npy',arr )

In [ ]:
def predict(img: np.ndarray, model_path: str) -> np.ndarray:
    model = np.load(model_path)   
    return (img - model[0])/model[1]

def train(img: np.ndarray, save_model_path: str) -> None:
    arr = np.array((np.mean(img), np.std(img)))
    np.save(save_model_path + 'model.npy', arr+'model.npy')

In [18]:
np.load('model.npy')

array([54.26754322, 73.24830192])

In [17]:
arr

array([54.26754322, 73.24830192])

In [22]:
np.unique(img)

array([  0,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 144, 145, 146,
       147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 158, 161, 162,
       163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
       176, 177, 179, 180, 181, 182, 183, 184, 185, 186, 187, 18